from math import factorial, pi, sqrt

import numpy as np


def zernike_radial(
        n: int,
        m_abs: int,
        r: np.ndarray,
) -> np.ndarray:
    """
    Evaluate the Zernike radial polynomial R_n^|m|(r).

    Args:
        n: Radial polynomial order.
        m_abs: Absolute azimuthal order |m|.
        r: Radial coordinates. Typically, r is defined on the unit interval
            [0, 1], although this function also evaluates the polynomial for
            values outside that range.

    Returns:
        Array with the same shape as r containing R_n^|m|(r).

    Notes:
        A valid Zernike radial polynomial requires:

            n >= |m|

        and

            n - |m| must be even.

        If either condition is not satisfied, the function returns zeros.

        The polynomial is evaluated as:

            R_n^m(r) =
                sum_{k=0}^{(n-m)/2}
                (-1)^k (n-k)! /
                [k! ((n+m)/2-k)! ((n-m)/2-k)!]
                r^(n-2k)
    """
    # Zernike polynomials are only defined for valid (n, |m|) combinations.
    if (n < m_abs) or ((n - m_abs) % 2 != 0):
        return np.zeros_like(r, dtype=float)

    out = np.zeros_like(r, dtype=float)
    nm_half = (n - m_abs) // 2

    # Accumulate the radial-polynomial terms.
    for k in range(nm_half + 1):
        num = factorial(n - k)
        den = (
                factorial(k)
                * factorial((n + m_abs) // 2 - k)
                * factorial(nm_half - k)
        )

        out += (
                ((-1) ** k)
                * num
                / den
                * (r ** (n - 2 * k))
        )

    return out


def zernike_value(
        n: int,
        m: int,
        R: np.ndarray,
        Theta: np.ndarray,
) -> np.ndarray:
    """
    Evaluate a normalized real-valued Zernike polynomial on the unit disk.

    Args:
        n: Radial order.
        m: Signed azimuthal order.
            - m = 0 uses the rotationally symmetric term.
            - m > 0 uses cos(m * Theta).
            - m < 0 uses sin(|m| * Theta).
        R: Radial-coordinate array with shape (...,).
        Theta: Angular-coordinate array in radians with shape (...,).

    Returns:
        Normalized Zernike polynomial values with the same shape as R.

    Notes:
        This uses a Noll-like normalization convention in which the basis
        functions are orthonormal on the unit disk with respect to the area
        integral. The normalization includes pi in the denominator.

        For m = 0:

            Z_n^0(r, theta) =
                sqrt((n + 1) / pi) * R_n^0(r)

        For m > 0:

            Z_n^m(r, theta) =
                sqrt(2(n + 1) / pi) * R_n^m(r) * cos(m theta)

        For m < 0:

            Z_n^m(r, theta) =
                sqrt(2(n + 1) / pi) * R_n^|m|(r) * sin(|m| theta)
    """
    m_abs = abs(m)
    Rnm = zernike_radial(n, m_abs, R)

    # Select the angular basis function and normalization factor.
    if m == 0:
        norm = sqrt((n + 1) / pi)
        ang = 1.0
    elif m > 0:
        norm = sqrt(2 * (n + 1) / pi)
        ang = np.cos(m * Theta)
    else:
        norm = sqrt(2 * (n + 1) / pi)
        ang = np.sin(m_abs * Theta)

    Z = norm * Rnm * ang

    return Z.astype(np.float32)


def get_basis_indices_same_order(num_terms: int):
    """
    Generate a stable sequence of Zernike mode indices (n, m).

    Args:
        num_terms: Number of Zernike modes to generate.

    Returns:
        List of (n, m) tuples with length equal to num_terms.

    Ordering:
        Modes are generated by increasing radial order n. For each n, only
        azimuthal orders m with matching parity are valid:

            n even -> m = 0, 2, 4, ..., n
            n odd  -> m = 1, 3, 5, ..., n

        For every nonzero azimuthal order, the positive cosine mode is added
        first, followed by the negative sine mode:

            (n, +m), (n, -m)

    Example:
        The beginning of the sequence is:

            (0, 0)
            (1, +1), (1, -1)
            (2, 0), (2, +2), (2, -2)
            ...
    """
    idx = []
    count = 0
    n = 0

    while count < num_terms:
        # Valid m values must have the same parity as n.
        m_vals = (
            range(0, n + 1, 2)
            if n % 2 == 0
            else range(1, n + 1, 2)
        )

        for m in m_vals:
            if count >= num_terms:
                break

            if m == 0:
                # Axisymmetric mode.
                idx.append((n, 0))
                count += 1
            else:
                # Add cosine-like (+m) and sine-like (-m) modes consecutively.
                idx.append((n, +m))
                count += 1

                if count < num_terms:
                    idx.append((n, -m))
                    count += 1

        n += 1

    return idx


def zernike_wavefront_at_points(
        coeffs,
        inds,
        x: np.ndarray,
        y: np.ndarray,
) -> np.ndarray:
    """
    Reconstruct a scalar wavefront from Zernike coefficients at arbitrary points.

    Args:
        coeffs: Sequence of Zernike expansion coefficients.
        inds: Sequence of corresponding (n, m) Zernike indices.
        x: x-coordinate array with shape (...,).
        y: y-coordinate array with shape (...,).

    Returns:
        Reconstructed wavefront array with the same shape as x and y.

    Notes:
        The wavefront is evaluated as:

            U(x, y) = sum_i c_i * Z_{n_i}^{m_i}(r, theta)

        where:

            r     = sqrt(x^2 + y^2)
            theta = arctan2(y, x)

        Values outside the unit disk, where r > 1, are explicitly set to zero.
    """
    # Convert Cartesian coordinates to polar coordinates.
    r = np.sqrt(x ** 2 + y ** 2)
    theta = np.arctan2(y, x)

    # Initialize the reconstructed wavefront.
    U = np.zeros_like(r, dtype=np.float32)

    # Unit-disk aperture mask.
    inside = r <= 1.0

    # Accumulate all nonzero Zernike basis contributions.
    for c, (n, m) in zip(coeffs, inds):
        if c == 0.0:
            continue

        U += c * zernike_value(n, m, r, theta)

    # Enforce zero wavefront outside the circular pupil.
    U[~inside] = 0.0

    return U.astype(np.float32)
